src/provider/chains/cosmos/provider.ts, src/provider/chains/cosmos/sdk/signing.ts, src/provider/chains/cosmos/tendermint.ts, src/types/chain.ts, src/types/provider.ts, tests/provider/chains/cosmos/provider.test.ts, tests/provider/chains/cosmos/tendermint.test.ts
1. 支持 CW20 （UnsignedTx 里加上了 type 字段，type 为空或 transfer 为普通转账，链可以自定义新值，CW20 转账是 cw20_transfer）
…
…
…
=> feat: support CW20

package.json, src/secret/bip32.ts, tsconfig.json
1. 修复在rn中使用crypto的问题
2. 修复BigInt的字面量写法在rn上非法的问题
…
…
=> fix: crypto hack for react-native and BigInt format used that invalid in react-native

package.json, src/provider/chains/cfx/provider.ts, src/provider/chains/eth/provider.ts, src/provider/chains/eth/sdk/eip1559-fee.ts, tests/provider/chains/cfx/provider.test.ts, tests/provider/chains/eth/provider.test.ts
Fix a couple of minor bugs.
No
UT
=> minor bug fixes

package.json, src/secret/bip32.ts, tsconfig.json
Fix a couple of integration problems
No
web/iOS/unittests
No
=> Fix a couple of integration problems

package.json, src/secret/curves/base.ts, src/secret/curves/elliptic.ts, src/secret/encryptors/aes256.ts, src/secret/hash.ts, src/secret/index.ts, tests/secret/index.test.ts, yarn.lock
1. fix conflux-address-js module resolution
2. introduce asmcrypto.js
3. add batch get keys functionalities to reduce the need of encryption/decryption
No
node.js/web/android
No
=> integration fix & performance improvement

package.json, src/secret/curves/elliptic.ts
On browser environment, bn.js's toBuffer function can't be used.
web/android
No
=> Fix bn.js related problem

package.json, src/provider/abc.ts, src/provider/chains/eth/provider.ts, src/provider/chains/eth/sdk/message.ts, src/provider/index.ts, src/types/provider.ts, tests/provider/chains/eth/provider.test.ts, tests/provider/chains/eth/sdk/message.test.ts, yarn.lock
=> Eth message

package.json, src/provider/chains/bch/index.ts, src/provider/chains/bch/provider.ts, src/provider/chains/btc/blockbook.ts, src/provider/chains/btc/index.ts, src/provider/chains/btc/provider.ts, src/provider/chains/btc/sdk/networks.ts, src/provider/chains/btc/sdk/vsize.ts, src/provider/index.ts, tests/provider/chains/btc-like/fixture.json, tests/provider/chains/btc-like/provider.test.ts, tests/provider/chains/btc/blockbook.test.ts, tests/provider/chains/btc/provider.test.ts, tests/provider/chains/btc/sdk/vsize.test.ts, yarn.lock
1. 接入 BTC
2. 测试 BTC
3. 支持 LTC, BCH, DOGE, BTG, DGB, NMC, VTC (暂不支持 DASH 和 ZEC，因为变动较大)
4. 测试 LTC, BCH, DOGE, BTG, DGB, NMC, VTC
…
…
…
=> Support BTC and BTC-like coins

src/provider/chains/btc/sdk/networks.ts, src/provider/index.ts, tests/provider/chains/btc-like/fixture.json
1. 支持 dash 并测试。原来 dash [新增的交易类型](https://dashcore.readme.io/docs/core-ref-transactions-special-transactions)不是给普通用户弄的，不理解 trezor-suite 代码为啥要加上那些新增字段，那新写的那些先不提交了，直接配置就可以了
…
…
…
=> feat: support dash

src/provider/chains/near/nearcli.ts, src/provider/chains/near/provider.ts, tests/provider/chains/near/provider.test.ts
=> feat: calculate gas limit for near tx

package.json, src/basic/exceptions.ts, src/provider/abc.ts, src/provider/chains/eth/provider.ts, src/provider/chains/eth/sdk/message.ts, src/provider/index.ts, tests/provider/chains/eth/sdk/message.test.ts, yarn.lock
1. eth supports hardware
…
…
…
=> feat: eth supports hardware

package.json, src/index.ts, yarn.lock
=> feat: use ethers

src/provider/chains/btc/provider.ts
=> feat: btc supports hardware

package.json, src/provider/chains/stc/provider.ts, yarn.lock
=> feat: stc supports hardware

src/provider/chains/cfx/provider.ts
=> feat: cfx support hardware

package.json, src/provider/chains/sol/provider.ts, yarn.lock
=> feat: sol support hardware

package.json, src/provider/abc.ts, src/provider/chains/btc/provider.ts, src/provider/chains/cfx/provider.ts, src/provider/chains/eth/provider.ts, src/provider/chains/sol/provider.ts, src/provider/chains/stc/provider.ts, yarn.lock
=> fix: add peerDependiency for sdk

.github/mergify.yml, package.json, src/provider/chains/cfx/provider.ts, src/provider/chains/cosmos/provider.ts, src/provider/chains/cosmos/sdk/signing.ts, src/provider/chains/cosmos/tendermint.ts, src/provider/chains/eth/provider.ts, src/provider/chains/near/provider.ts, src/secret/encryptors/aes256.ts, tests/provider/chains/eth/provider.test.ts
- remove duplicate eth address prefix check 
- require nonce for eth unsigned transactions, to avoid sending out next transaction by mistake
- fix lint errors
=> Some improvements

package.json, src/provider/chains/eth/geth.ts
=> feat: add ethers.js provider on geth

package.json, src/provider/abc.ts, src/provider/chains/sol/solana.ts, src/provider/index.ts
=> fix: add options params for rpc client

package.json, patches/@metamask+eth-sig-util+4.0.1.patch, src/provider/chains/eth/sdk/message.ts, yarn.lock
=> fix: legacyToBuffer patch
